import React from 'react';
import { Download, Share2, Copy, Check } from 'lucide-react';
import type { AnalysisResponse } from '../types';

interface ShareExportProps {
  result: AnalysisResponse;
}

export const ShareExport: React.FC<ShareExportProps> = ({ result }) => {
  const [copied, setCopied] = React.useState(false);

  const handleDownloadJSON = () => {
    const dataStr = JSON.stringify(result, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    const productName = result.data?.detailedAnalysis?.productInfo?.name || 'analysis';
    link.download = `healthlens-${productName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadText = () => {
    const data = result.data;
    if (!data) return;

    let text = '═══════════════════════════════════════\n';
    text += '    HealthLens Analysis Report\n';
    text += '═══════════════════════════════════════\n\n';

    // Quick Summary
    text += `📋 QUICK SUMMARY\n${'-'.repeat(40)}\n${data.quickSummary}\n\n`;

    // Product Info
    if (data.detailedAnalysis?.productInfo) {
      const info = data.detailedAnalysis.productInfo;
      text += `📦 PRODUCT INFORMATION\n${'-'.repeat(40)}\n`;
      if (info.name) text += `Name: ${info.name}\n`;
      if (info.manufacturer) text += `Manufacturer: ${info.manufacturer}\n`;
      if (info.category) text += `Category: ${info.category}\n`;
      if (info.primaryPurpose) text += `Purpose: ${info.primaryPurpose}\n`;
      text += '\n';
    }

    // Health Score
    if (data.healthScore) {
      text += `📊 HEALTH SCORE\n${'-'.repeat(40)}\n`;
      if (data.healthScore.nutritionalValue !== undefined) 
        text += `Nutritional Value: ${data.healthScore.nutritionalValue}/10\n`;
      if (data.healthScore.ingredientQuality !== undefined) 
        text += `Ingredient Quality: ${data.healthScore.ingredientQuality}/10\n`;
      if (data.healthScore.processingLevel !== undefined) 
        text += `Processing Level: ${data.healthScore.processingLevel}/10\n`;
      if (data.healthScore.overall !== undefined) 
        text += `Overall Score: ${data.healthScore.overall}/10\n`;
      text += '\n';
    }

    // Warnings
    if (data.warnings && data.warnings.length > 0) {
      text += `⚠️  HEALTH ALERTS\n${'-'.repeat(40)}\n`;
      data.warnings.forEach((warning, i) => {
        text += `${i + 1}. [${warning.severity.toUpperCase()}] ${warning.category}\n`;
        text += `   ${warning.message}\n\n`;
      });
    }

    // Recommendations
    if (data.recommendations && data.recommendations.length > 0) {
      text += `💡 RECOMMENDATIONS\n${'-'.repeat(40)}\n`;
      data.recommendations.forEach((rec, i) => {
        text += `${i + 1}. ${rec}\n`;
      });
      text += '\n';
    }

    // Disclaimer
    text += `\n${'═'.repeat(40)}\n`;
    text += 'MEDICAL DISCLAIMER\n';
    text += `${'═'.repeat(40)}\n`;
    text += 'This analysis is for informational purposes only.\n';
    text += 'Always consult your healthcare provider for medical advice.\n\n';
    text += `Generated by HealthLens • ${new Date().toLocaleString()}\n`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const productName = data.detailedAnalysis?.productInfo?.name || 'analysis';
    link.download = `healthlens-${productName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyToClipboard = async () => {
    const data = result.data;
    if (!data) return;

    const text = `HealthLens Analysis:\n${data.quickSummary}\n\nView full report at: ${window.location.href}`;
    
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  const handleShare = async () => {
    const data = result.data;
    if (!data) return;

    const shareData = {
      title: 'HealthLens Analysis',
      text: data.quickSummary,
      url: window.location.href,
    };

    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        // Fallback to copy
        handleCopyToClipboard();
      }
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  return (
    <div className="bg-white rounded-lg shadow-md p-4">
      <h3 className="text-sm font-semibold text-gray-700 mb-3">Export & Share</h3>
      <div className="flex flex-wrap gap-2">
        <button
          onClick={handleDownloadJSON}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm"
        >
          <Download size={16} />
          Download JSON
        </button>
        <button
          onClick={handleDownloadText}
          className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors text-sm"
        >
          <Download size={16} />
          Download TXT
        </button>
        <button
          onClick={handleCopyToClipboard}
          className="flex items-center gap-2 px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors text-sm"
        >
          {copied ? <Check size={16} /> : <Copy size={16} />}
          {copied ? 'Copied!' : 'Copy Summary'}
        </button>
        <button
          onClick={handleShare}
          className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm"
        >
          <Share2 size={16} />
          Share
        </button>
      </div>
    </div>
  );
};
